import "./globals.css";
import { Fira_Sans } from "next/font/google";
// import localFont from 'next/font/local';

const fira = Fira_Sans({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-fira",
});

// const grosa = localFont({
//   src: [
//     {
//       path: '../../public/fonts/Grosa/Grosa-Regular.woff2',
//       weight: '500',
//       style: 'normal',
//     },
//   ],
//   variable: '--font-grosa',
// });

export const metadata = {
  title: "Bidbutler",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fira.className}>{children}</body>
    </html>
  );
}
